title: Nuoframework Web
url: "https://nuoframework.github.io"
baseurl: "/"

remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://liktr.ee/nuofrwk"
footer_text: "Enlace a RRSS"

sass:
    style: compressed
    sass_dir: /_sass

nav:
 - name: "Sobre Mi"
   link: "about"
 - name: "Contacto"
   link: "contact"

