title: Pablo Arrabal as Nuoframework
url: "https://nuoframework.github.io"
baseurl: "/"

remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: G-5LV9LLG044

footer: yes
footer_url: "https://linktr.ee/nuofrwk"
footer_text: "Enlace a RRSS"

sass:
    style: compressed
    sass_dir: /_sass

nav:
 - name: "Sobre Mi"
   link: "index"
 - name: "Contacto"
   link: "contact"
 - name: "Blog"
   link: "https://blognuoframework.github.io"


