title: Nuoframework Web
url: "https://pabloarrabal.cf"
baseurl: "/inicio"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://liktr.ee/nuofrwk"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Sobre Mi"
   link: "/about/"
 - name: "CV"
   link: "resume.pdf"
 - name: "Contacto"
   link: "contact"
