title: Pablo Arrabal as Nuoframework
url: "https://nuoframework.github.io"
baseurl: "/"

remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: G-5LV9LLG044

footer: yes
footer_url: "https://liktr.ee/nuofrwk"
footer_text: "Enlace a RRSS"

sass:
    style: compressed
    sass_dir: /_sass

nav:
 - name: "Sobre Mi"
   link: "index"
 - name: "Contacto"
   link: "contact"

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-5LV9LLG044"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-5LV9LLG044');
</script>
